config/routes.rb
Rails.application.routes.draw do
  resources :locations

  root 'posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :posts
  post 'posts/:id/hide' => 'posts#hide', as: :delete_post
  get 'maps' => 'locations#maps'
  post 'posts/help' => 'posts#help', as: :help_post
  post 'posts/cancel_help' => 'posts#cancel_help', as: :cancel_help_post
  post 'posts/submit' => 'posts#submit', as: :request_post

  get 'privacy' => 'pages#privacy'
  get 'thanks' => 'pages#thanks'


  resources :sessions, only: [:create, :destroy]
  resource :main, only: [:show]
  get 'institutions' => 'institutions#index'

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_and_belongs_to_many :helping_users, class_name: "User",join_table:"helping_users", foreign_key: "post_id", dependent: :destroy
  belongs_to :location
  has_and_belongs_to_many :requirements

  accepts_nested_attributes_for :location

  scope :containing, ->(text){
    self.where(includes_filter(text))
  }

  # Pagination
  self.per_page =3

  before_save :default_values
  def default_values
    self.status ||= 'active' # note self.status = 'P' if self.status.nil? might be safer (per @frontendbeauty)
  end

  def search_string
    post=self
    reqs = ""
    post.requirements.each do |req|
      reqs = reqs+ req.name
    end
    reqs = reqs + post.content
    reqs = reqs + post.user.name
    reqs.downcase
  end

  def includes_filter(text)
    self.search_string.include? text.downcase
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :log_in, :except => :index

  before_action :set_post, only: [:show, :edit, :update, :destroy, :help, :cancel_help]

  before_action :common_content


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where('status != ?', 'hidden')
    @posts = @posts.order("created_at DESC")
    # @posts = @posts.where('created_at > ?',  20.hours.ago)
    @shared_post = Post.first
    if params['category']
      @posts = @posts.where(category: params['category'])
    end
    if params['contains']
     @posts = @posts.to_a.select {|post| post.includes_filter(params['contains'])}
    end
    # @posts.sort {|a,b| (a.created_at <=> b.created_at)}.reverse!
    # @posts.sort  {|a,b| a.helping_users.count <=> b.helping_users.count}
    @posts  = @posts.paginate(:page => (params[:page] || 1), :per_page =>3)
  end

  def hide
    post = Post.find(params[:id])
    post.update(status: "hidden")
    respond_to do |format|
      format.html { redirect_to "/posts", notice: 'Post removido.' }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.location = Location.new
    @post.category = params[:category].to_i
    #instance = {}
    # if [0,1].include?(params[:category].to_i)
     # instance['category'] = params[:category]
    # end
    #puts "AQUI ESTA LA CATEGORIA: "
    #puts instance['category']
    #puts [0,1].include?(params[:category].to_i)
    #instance['post'] = Post.new
    #instance['post'].location = Location.new
    @requirements = Requirement.all
    #@instance = instance
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    puts post_params
    @post = Post.new(post_params)
    params[:requirement].each do |key, req|
      if req["id"] =="1"
        item = Requirement.find(key)
        @post.requirements << item
      end
    end
    @post.errors.messages
     if @post.save
        # format.html { render :index, notice: 'Post was successfully created.' }
        # format.json { render :index, status: :created, location: @post }
        redirect_to posts_path
      else
        render text: @post.errors.messages.to_s
      end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.update(status: "hidden")
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post ha sido borrado.' }
      format.json { head :no_content }
    end
  end

  def help
    @shared_post = Post.find(params[:id])
    if @post.helping_users.where(id: current_user.id).empty?
      @post.helping_users << current_user
    end
    respond_to do |format|
      format.js {render 'show_modal'}
    end
    render plain:"true"
  end

  def cancel_help
    respond_to do |format|
      if @post.helping_users.delete(current_user)
        format.html { redirect_to posts_url }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render posts_url}
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def submit
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

  def common_content
    @shared_post
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      par = params.require(:post).permit(:content, :phone, :category, :location_id, location_attributes: [:id, :address, :latitude, :longitude, :state])
      par['user_id'] = current_user.id
      par
    end

  def log_in
    unless current_user
      redirect_to "/auth/facebook"
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_filters.html.erb
<div style="text-align: center">
  <a href="/posts?category=0" class="button btn btn-success">Ayudar</a>
  <a href="/posts?category=1" class="button btn btn-danger">Encontrar Ayuda</a>
</div>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <h3 class="red">
      <% if @post.category=="0" %>
          ¿Qué necesitas?
      <% else %>
          ¿Con qué puedo ayudar?
      <% end %>
    </h3>
    <div class="help-type">
      <% if @requirements -%>
          <% @requirements.each do |requirement| -%>

              <%= fields_for 'requirement[]' , requirement do |requirement_fields| -%>

                  <%= requirement.name %>
                  <%= requirement_fields.check_box :id %>
                  <br>
              <% end -%>
          <% end -%>
      <% end -%>
      <br />
    </div>
    <br/>
    <h3 class="red">Descripción:</h3>
    <%= f.text_area :content, rows:5, cols:80, required: true %><br />
    <h3 class="red">Ubicación :</h3>
    <div id="mapPost" style="height:250px;width:100%;margin:0 auto;"></div>
    <%= f.fields_for :location do |fact| %>
        <%= fact.hidden_field :address %>
        <%= fact.hidden_field :latitude %>
        <%= fact.hidden_field :longitude %>
    <% end %>
    <h3 class="red">Teléfono de Contacto:</h3>
    <%= f.text_field :phone , class:"big-input", required: true%><br />
    <%= f.hidden_field :category, value: @post.category %>

    <br>
    <!--<div id="reminder" class="alert alert-danger" style="display: none" role="alert"></div>-->
    <div class="buttons">
      <%= button_tag  'Cancelar', type:'button', onclick: "location.href = '/posts'", class:"button cancelar" %>

      <%= f.submit 'Guardar', class:"button aceptar" %>
    </div>

    <div class="logo">
      <%= image_tag('XMX.png') %>
    </div>
<% end %>

<script>
    /*$('#new_post').submit(function() {  //When a form is submitted...
        if ($('#post_location_attributes_latitude').val() != 12) { //To see if it is empty...
            $( '#reminder' ).toggle().text( "¡No olvides de poner tu ubicación!" ).show().fadeOut( 4000 );
            return false;            //Don't submit the form
        }
    });*/
</script>

app/views/posts/_show_modal.html.erb
<div class="row">
  <div class="col-sm-4">
    Whatsapp
    <a href="https://api.whatsapp.com/send?phone=521<%= @shared_post.phone %>" target="_blank">
      <img class="img-responsive" src="images/whatsapp.png">
    </a>
  </div>
  <div class="col-sm-4">
    Facebook
    <a href="https://<%= @shared_post.user.fb_profile %>" target="_blank">
      <img class="img-responsive" src="images/facebook.png">
    </a>
  </div>
  <div class="col-sm-4">
    Teléfono
    <a href="tel:52<%= @shared_post.phone %>">
      <img class="img-responsive" src="images/phone.png">
    </a>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div style="margin-top:150px;"></div>
<%= render 'filters' %>
<% @posts.each do |post| %>
  <div class="post-container">
    <div class="post">
      <h4 class="center hour"><%= post.created_at.in_time_zone(-5).strftime("%b %e, %l:%M %p") %></h4>
      <div class="image-container">
        <%= image_tag(post.user.picture) %>
      </div>
      <div class="post-info">
        <h3><%= post.user.name %></h3>
        <p>
           <% if post.category == "0"%>
              <span class="red">
                Necesito ayuda
              </span>
          <% elsif post.category =="1"%>
              <span class="green">
                Quiero ayudar
              </span>
          <% end %>
           con
          <%= post.requirements.find_each do |req| %>
              <span class="underline"><%= req.name %></span>,
          <% end %>
          en <i class="fa fa-map-marker" aria-hidden="true"></i> <b><%= post.location.address %></b><hr style="border-color:#000"> <%= post.content %><br/></p>
      </div>
      <% if post.category == "0"%>
          <span>Ayudado por: <%=post.helping_users.count %> persona(s)</span>
    <% end %>
    </div>
    <div class="my-button-container">
      <% if post.category == "1" %>
        <% if post.user.id == current_user&.id %>
            <%= button_to("Borrar", delete_post_path(id: post), method: :post, class:"my-button b-red") %>
        <% elsif  post.category == "1" %>
            <%= button_to("Solicitar", post_path(id: post), method: :get, class: "my-button b-red" ) %>
        <% end %>
      <% else %>
        <% if post.user.id == current_user&.id %>
            <%= button_to("Borrar", delete_post_path(id: post), method: :post, class:"my-button b-red") %>
        <% elsif post.category == "0" %>
            <% if post.helping_users.where(id: current_user&.id).empty? %>
              <%= button_to("Ayudar", post_path(id: post), id:"help", method: :get, class: "my-button b-green") %>
              <% else %>
                  <%= button_to("Cancelar", cancel_help_post_path(id: post), method: :post, class: "my-button b-red", :remote => true ) %>
            <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

<div class="digg_pagination center">
  <%= will_paginate @posts,  :previous_label => t('<- Anterior'), :next_label => t('Siguiente ->'), :page_links => false%>
</div>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<%= render 'application/navigation' %>
<div class="row" style="margin-top:100px">
  <div class="col-md-offset-2 col-md-2 center col-sm-8 col-sm-offset-2">
    <h1 class="center">Whatsapp</h1>
    <a href="https://api.whatsapp.com/send?phone=521<%= @post.phone %>" target="_blank">
      <img class="img-responsive" style="cursor: pointer;width:250px;" src="/images/whatsapp.png">
    </a>
    <h3><%= @post.phone %></h3>
  </div>
  <div class="col-md-2 center col-sm-8 col-sm-offset-2 col-md-offset-1">
    <h1 class="center">Facebook</h1>
    <a href="https://<%= @post.user.fb_profile %>" target="_blank">
      <img class="img-responsive" style="cursor: pointer; width:250px; " src="/images/facebook.png">
    </a>
    <h4><%= @post.user.fb_profile %></h4>
  </div>
  <div class="col-md-2 center col-sm-8 col-sm-offset-2 col-md-offset-1">
    <h1 class="center">Teléfono</h1>
    <a href="tel:52<%= @post.phone %>">
      <img class="img-responsive" style="cursor: pointer;width:250px;" src="/images/phone.png">
    </a>
    <h3><%= @post.phone %></h3>
  </div>

</div>
<div class="buttons" style="text-align: center; margin-top:100px">
  <%= link_to 'Atrás', :back, class:"button cancelar" %>
</div>