config/routes.rb
Rails.application.routes.draw do
  resources :locations

  root 'posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :posts
  post 'posts/:id/hide' => 'posts#hide', as: :delete_post
  get 'maps' => 'locations#maps'
  post 'posts/help' => 'posts#help', as: :help_post
  post 'posts/cancel_help' => 'posts#cancel_help', as: :cancel_help_post
  post 'posts/submit' => 'posts#submit', as: :request_post

  get 'privacy' => 'pages#privacy'
  get 'thanks' => 'pages#thanks'


  resources :sessions, only: [:create, :destroy]
  resource :main, only: [:show]
  get 'institutions' => 'institutions#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception



    private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navigation.html.erb
<ul class="nav-bar" style="overflow:scroll">
  <li class="logo"><%= link_to image_tag('XMX.png'), posts_url, style: "padding:0" %></li>
  <li class="nav-button"><%= link_to 'Quiero Ayudar', new_post_path(:category => 1), class: "green-button" %></li>
  <li class="nav-button"><%= link_to 'Necesito Ayuda', new_post_path(:category => 0), class: "red-button" %></li>
  <!--<li class="nav-button"><%= link_to 'Aviso Importante', "/" %></li>-->
  <li class="nav-button"><%= link_to '¿Eres desarrollador? ¡Colabora con nosotros!', "https://github.com/Avtelyes/PorMexico" %></li>
  <li class="nav-button filter-input">
    <form action="/posts" name="filter" id="filter">
      <input type="text" id="contains" name="contains">
      <button type="submit" class="nav-image">
        <i class="fa fa-search" aria-hidden="true" ></i>
      </button>
    </form>
  </li>



  <li><%= link_to image_tag('map.png', class:"nav-image"), "/maps" %></a></li>
  <li><%= link_to image_tag('donate.png', class:"nav-image opacidad"), "/institutions" %></a></li>
</ul>
<div style="margin-top:100px;"></div>