config/routes.rb
Rails.application.routes.draw do
  resources :locations

  root 'posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :posts
  post 'posts/:id/hide' => 'posts#hide', as: :delete_post
  get 'maps' => 'locations#maps'
  post 'posts/help' => 'posts#help', as: :help_post
  post 'posts/cancel_help' => 'posts#cancel_help', as: :cancel_help_post
  post 'posts/submit' => 'posts#submit', as: :request_post

  get 'privacy' => 'pages#privacy'
  get 'thanks' => 'pages#thanks'


  resources :sessions, only: [:create, :destroy]
  resource :main, only: [:show]
  get 'institutions' => 'institutions#index'

end

app/models/location.rb
class Location < ApplicationRecord
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode, :if => :address_changed? or :longitude_changed?
  has_one :post
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  def maps
    #@locations = ActiveRecord::Base.connection.execute("foo")
    @NeedLocations = ActiveRecord::Base.connection.exec_query("SELECT * FROM locations INNER JOIN posts ON posts.location_id = locations.id AND posts.category = 0;")
    #puts @NeedLocations
    @OfferLocations = ActiveRecord::Base.connection.exec_query("SELECT * FROM locations INNER JOIN posts ON posts.location_id = locations.id AND posts.category = 1;")
    pairs = []
    @NeedLocations.as_json.each do | item |
      pairs << {lat: item['latitude'], lng: item['longitude'], status: item['status']}
    end
    @pairsNeed = pairs
    pairs = []
    @OfferLocations.as_json.each do | item |
      pairs << {lat: item['latitude'], lng: item['longitude'], status: item['status']}
    end
    @pairsOffer = pairs
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :latitude, :longitude, :state)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(location) do |f| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
    <fieldset class="form-group">
      <%= f.label :address, 'Address' %>
      <%= f.text_field :address, class: "form-control" %>
      <small class="text-muted">You can also enter IP. Your IP is <%= request.ip %></small>
    </fieldset>
<% end %>
<div id="mapN" style="height:300px;width:100vw;margin:0 auto;"></div>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= location.state %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div id="map" style="height:300px;width:100vw;margin:0 auto;"></div>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/maps.html.erb
<%= render 'application/navigation' %>

<h1>Necesita Ayuda</h1>
<div id="mapN" style="height:580px;width:100%;margin:0 auto;"></div>
<h1>Ofrece Ayuda</h1>
<div id="mapO" style="height:580px;width:100%;margin:0 auto;"></div>
<iframe src="https://www.google.com/maps/d/embed?mid=13B_gbt3e5RWk_6xQoQ15xxhGOFs" width="100%" height="580"></iframe>
<div id="need_locations_list">
  <%= hidden_field :location, :value => @pairsNeed%>
</div>
<div id="offer_locations_list">
  <%= hidden_field :location, :value => @pairsOffer%>
</div>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<p>
  <strong>State:</strong>
  <%= @location.state %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>